(defvar x)  
(defvar r)
(defun cuadrado(x) (* x x))
(print "Programa que de el cuadrado de un numero")  
(print "Dame el valor de x:") 
(SETQ x (READ))
(setf r (cuadrado x))
(print "El resultado de la operacion es: ")
(print r) 
