(defvar x)  
(defvar y)  
(defvar z)
(defvar w)
(defvar r)
(defun operacion(x y z w)(+ x (- y (* z w))))
(print "Programa que haga la operacion x+y-z*w")  
(print "Dame el valor de x:") 
(SETQ x (READ))
(print "Dame el valor de y:") 
(SETQ y (READ))
(print "Dame el valor de z:")
(SETQ z (READ))
(print "Dame el valor de w:")
(SETQ w (READ))
(setf r (operacion x y z w))
(print "El resultado de la operacion es: ")
(print r)